#!/usr/bin/env bash
# Cloudflare IP ranges → ufw (80/443 from Cloudflare only) + the Caddy matcher (cloudflare_peer) that decides when
# CF-Connecting-IP and the Cloudflare Access e-mail are trusted. Run as root; idempotent.
# Installed by bootstrap.sh as /usr/local/sbin/otto-cloudflare-ips (root-owned copy) and run weekly by otto-cloudflare-ips.timer.
# The lists come from Cloudflare's own https://www.cloudflare.com/ips-v4 and /ips-v6. A short or malformed answer changes nothing.
set -euo pipefail

SNIPPET=/etc/caddy/otto.d/cloudflare.caddy
CACHE=/etc/otto/cloudflare-ips.txt
TAG=otto-cloudflare

[[ $EUID -eq 0 ]] || { echo "run as root" >&2; exit 1; }

fetch() {   # $1 = v4|v6
	curl -fsS --proto '=https' --tlsv1.2 --max-time 20 --retry 3 "https://www.cloudflare.com/ips-$1"
}

v4=$(fetch v4 | tr -d '\r' | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$' || true)
v6=$(fetch v6 | tr -d '\r' | grep -E '^[0-9a-fA-F:]+/[0-9]{1,3}$' || true)
n4=$(printf '%s\n' "$v4" | grep -c . || true)
n6=$(printf '%s\n' "$v6" | grep -c . || true)
if (( n4 < 10 || n6 < 4 )); then
	echo "otto-cloudflare-ips: got $n4 IPv4 / $n6 IPv6 ranges — looks wrong, keeping the current rules" >&2
	exit 1
fi
ranges=$(printf '%s\n%s\n' "$v4" "$v6")

# --- Caddy: (cloudflare_peer) defines @cloudflare = the TCP peer is Cloudflare
mkdir -p "$(dirname "$SNIPPET")"
tmp=$(mktemp "$SNIPPET.XXXXXX")
{
	echo "# Generated by otto-cloudflare-ips (infra/cloudflare-ips.sh) on $(date -u +%FT%TZ) — do not edit, it is rewritten weekly."
	echo "(cloudflare_peer) {"
	printf '\t@cloudflare remote_ip %s\n' "$(printf '%s\n' "$ranges" | tr '\n' ' ' | sed 's/ *$//')"
	echo "}"
} >"$tmp"
chmod 0644 "$tmp"
changed=0
if ! cmp -s "$tmp" "$SNIPPET" 2>/dev/null; then
	# the timestamp line alone is not a change
	if [[ ! -f $SNIPPET ]] || ! diff -q <(tail -n +2 "$tmp") <(tail -n +2 "$SNIPPET") >/dev/null; then
		changed=1
		mv "$tmp" "$SNIPPET"
	fi
fi
rm -f "$tmp"
printf '%s\n' "$ranges" >"$CACHE"

# --- ufw: allow 80,443/tcp from each range; drop ranges Cloudflare no longer lists
if command -v ufw >/dev/null; then
	while read -r cidr; do
		[[ -n $cidr ]] || continue
		ufw allow proto tcp from "$cidr" to any port 80,443 comment "$TAG" >/dev/null
	done <<<"$ranges"
	ufw show added 2>/dev/null | grep -F "comment '$TAG'" | sed -nE 's/.* from ([^ ]+) to any port 80,443.*/\1/p' |
		while read -r old; do
			if ! grep -qxF "$old" <<<"$ranges"; then
				ufw delete allow proto tcp from "$old" to any port 80,443 >/dev/null && echo "otto-cloudflare-ips: removed $old"
			fi
		done
fi

if (( changed )) && systemctl is-active --quiet caddy; then
	systemctl reload caddy && echo "otto-cloudflare-ips: Caddy reloaded"
fi
echo "otto-cloudflare-ips: $n4 IPv4 + $n6 IPv6 Cloudflare ranges in ufw and $SNIPPET"
